apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lambo-bot-ing
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: lambo-bot-ing
              servicePort: 80